/**
 * Professional seed records for Indian Companies and MNCs operating in India.
 * Neutral reference data without unverified official claims.
 */

const indianCompanies = [
  {
    name: 'Tata Consultancy Services (TCS)',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Mumbai, Maharashtra, India',
    indiaLocations: ['Mumbai', 'Bengaluru', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Delhi', 'Noida', 'Ahmedabad', 'Kochi'],
    website: 'https://www.tcs.com',
    companySize: '10,000+',
    foundedYear: 1968,
    isVerified: false,
    description: 'Global leader in IT services, consulting, and business solutions with extensive delivery centres and technology innovation hubs across India.',
  },
  {
    name: 'Infosys',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Bengaluru, Karnataka, India',
    indiaLocations: ['Bengaluru', 'Pune', 'Hyderabad', 'Chennai', 'Mysuru', 'Chandigarh', 'Thiruvananthapuram', 'Bhubaneswar'],
    website: 'https://www.infosys.com',
    companySize: '10,000+',
    foundedYear: 1981,
    isVerified: false,
    description: 'Pioneering global digital services and consulting enterprise enabling clients in over 50 countries to navigate digital transformation.',
  },
  {
    name: 'Wipro',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Bengaluru, Karnataka, India',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Pune', 'Chennai', 'Kolkata', 'Noida', 'Gurugram', 'Coimbatore'],
    website: 'https://www.wipro.com',
    companySize: '10,000+',
    foundedYear: 1945,
    isVerified: false,
    description: 'Leading global information technology, consulting, and business process services company harnessing cognitive computing, cloud, and analytics.',
  },
  {
    name: 'HCLTech',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Noida, Uttar Pradesh, India',
    indiaLocations: ['Noida', 'Bengaluru', 'Chennai', 'Hyderabad', 'Pune', 'Lucknow', 'Madurai', 'Nagpur'],
    website: 'https://www.hcltech.com',
    companySize: '10,000+',
    foundedYear: 1976,
    isVerified: false,
    description: 'Global technology company delivering industry-leading capabilities centered around digital, engineering, and cloud services.',
  },
  {
    name: 'Tech Mahindra',
    category: 'Indian Company',
    industry: 'Telecommunications',
    headquarters: 'Pune, Maharashtra, India',
    indiaLocations: ['Pune', 'Hyderabad', 'Bengaluru', 'Chennai', 'Mumbai', 'Noida', 'Chandigarh', 'Nagpur'],
    website: 'https://www.techmahindra.com',
    companySize: '10,000+',
    foundedYear: 1986,
    isVerified: false,
    description: 'Specialist in digital transformation, consulting, and business re-engineering services with deep focus on 5G and telecommunications engineering.',
  },
  {
    name: 'LTIMindtree',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Mumbai, Maharashtra, India',
    indiaLocations: ['Mumbai', 'Bengaluru', 'Pune', 'Hyderabad', 'Chennai', 'Kolkata', 'Coimbatore'],
    website: 'https://www.ltimindtree.com',
    companySize: '10,000+',
    foundedYear: 1996,
    isVerified: false,
    description: 'Global technology consulting and digital solutions company enabling enterprises to reimagine business models and accelerate growth.',
  },
  {
    name: 'Persistent Systems',
    category: 'Indian Company',
    industry: 'Product Companies',
    headquarters: 'Pune, Maharashtra, India',
    indiaLocations: ['Pune', 'Bengaluru', 'Hyderabad', 'Nagpur', 'Goa'],
    website: 'https://www.persistent.com',
    companySize: '10,000+',
    foundedYear: 1990,
    isVerified: false,
    description: 'Trusted Digital Engineering and Enterprise Modernization partner helping companies engineer modern software products and platforms.',
  },
  {
    name: 'Mphasis',
    category: 'Indian Company',
    industry: 'Banking & Finance',
    headquarters: 'Bengaluru, Karnataka, India',
    indiaLocations: ['Bengaluru', 'Pune', 'Chennai', 'Mumbai', 'Hyderabad', 'Noida'],
    website: 'https://www.mphasis.com',
    companySize: '10,000+',
    foundedYear: 2000,
    isVerified: false,
    description: 'Information technology services and solutions provider specializing in cloud and cognitive services for banking, financial services, and insurance.',
  },
  {
    name: 'Coforge',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Noida, Uttar Pradesh, India',
    indiaLocations: ['Noida', 'Bengaluru', 'Hyderabad', 'Mumbai', 'Pune', 'Gurugram'],
    website: 'https://www.coforge.com',
    companySize: '10,000+',
    foundedYear: 1992,
    isVerified: false,
    description: 'Global digital services and solutions provider that leverages emerging technologies to deliver real-world business impact.',
  },
  {
    name: 'Zoho',
    category: 'Indian Company',
    industry: 'Product Companies',
    headquarters: 'Chennai, Tamil Nadu, India',
    indiaLocations: ['Chennai', 'Tenkasi', 'Salem', 'Tirunelveli', 'Bengaluru'],
    website: 'https://www.zoho.com',
    companySize: '10,000+',
    foundedYear: 1996,
    isVerified: false,
    description: 'SaaS pioneer providing a comprehensive suite of cloud software applications for CRM, finance, project management, and enterprise collaboration.',
  },
  {
    name: 'Freshworks',
    category: 'Indian Company',
    industry: 'Product Companies',
    headquarters: 'Chennai, Tamil Nadu, India',
    indiaLocations: ['Chennai', 'Bengaluru', 'Hyderabad'],
    website: 'https://www.freshworks.com',
    companySize: '5,000-10,000',
    foundedYear: 2010,
    isVerified: false,
    description: 'Innovative software-as-a-service company creating modern, AI-powered customer engagement and employee service management platforms.',
  },
  {
    name: 'Tata Technologies',
    category: 'Indian Company',
    industry: 'Automotive',
    headquarters: 'Pune, Maharashtra, India',
    indiaLocations: ['Pune', 'Bengaluru', 'Jamshedpur', 'Chennai'],
    website: 'https://www.tatatechnologies.com',
    companySize: '10,000+',
    foundedYear: 1989,
    isVerified: false,
    description: 'Global product engineering and digital services company delivering turnkey automotive engineering, EV platforms, and aerospace solutions.',
  },
  {
    name: 'Tata Elxsi',
    category: 'Indian Company',
    industry: 'Product Companies',
    headquarters: 'Bengaluru, Karnataka, India',
    indiaLocations: ['Bengaluru', 'Pune', 'Chennai', 'Thiruvananthapuram', 'Hyderabad'],
    website: 'https://www.tataelxsi.com',
    companySize: '10,000+',
    foundedYear: 1989,
    isVerified: false,
    description: 'Provider of design and technology services for automotive, broadcast, communications, healthcare, and transportation industries.',
  },
  {
    name: 'L&T Technology Services',
    category: 'Indian Company',
    industry: 'Manufacturing',
    headquarters: 'Vadodara / Mumbai, India',
    indiaLocations: ['Bengaluru', 'Vadodara', 'Mumbai', 'Chennai', 'Pune', 'Mysuru', 'Hyderabad'],
    website: 'https://www.ltts.com',
    companySize: '10,000+',
    foundedYear: 2012,
    isVerified: false,
    description: 'Pure-play engineering research and development (ER&D) services company offering engineering design, prototyping, and smart manufacturing.',
  },
  {
    name: 'Cyient',
    category: 'Indian Company',
    industry: 'Manufacturing',
    headquarters: 'Hyderabad, Telangana, India',
    indiaLocations: ['Hyderabad', 'Bengaluru', 'Pune', 'Noida', 'Visakhapatnam', 'Warangal'],
    website: 'https://www.cyient.com',
    companySize: '10,000+',
    foundedYear: 1991,
    isVerified: false,
    description: 'Global engineering, manufacturing, and digital technology solutions company delivering innovative design-led engineering systems.',
  },
  {
    name: 'KPIT Technologies',
    category: 'Indian Company',
    industry: 'Automotive',
    headquarters: 'Pune, Maharashtra, India',
    indiaLocations: ['Pune', 'Bengaluru', 'Kochi'],
    website: 'https://www.kpit.com',
    companySize: '10,000+',
    foundedYear: 1990,
    isVerified: false,
    description: 'Global technology partner specializing in automotive and mobility software solutions, autonomous driving, connected vehicles, and EV powertrains.',
  },
  {
    name: 'Mastek',
    category: 'Indian Company',
    industry: 'Consulting',
    headquarters: 'Mumbai, Maharashtra, India',
    indiaLocations: ['Mumbai', 'Pune', 'Chennai', 'Noida', 'Ahmedabad'],
    website: 'https://www.mastek.com',
    companySize: '5,000-10,000',
    foundedYear: 1982,
    isVerified: false,
    description: 'Turnkey and trusted digital engineering and cloud transformation partner executing enterprise modernization across public and private sectors.',
  },
  {
    name: 'Hexaware Technologies',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Navi Mumbai, Maharashtra, India',
    indiaLocations: ['Mumbai', 'Chennai', 'Pune', 'Bengaluru', 'Noida', 'Coimbatore'],
    website: 'https://www.hexaware.com',
    companySize: '10,000+',
    foundedYear: 1990,
    isVerified: false,
    description: 'Next-generation IT, BPO, and consulting services organization specializing in AI, automation, and cloud-first architectures.',
  },
  {
    name: 'Birlasoft',
    category: 'Indian Company',
    industry: 'IT & Software',
    headquarters: 'Pune, Maharashtra, India',
    indiaLocations: ['Pune', 'Noida', 'Bengaluru', 'Chennai', 'Hyderabad'],
    website: 'https://www.birlasoft.com',
    companySize: '10,000+',
    foundedYear: 1990,
    isVerified: false,
    description: 'Enterprise digital and IT services provider combining domain, enterprise, and digital technologies to transform business processes.',
  },
  {
    name: 'Nagarro India',
    category: 'Indian Company',
    industry: 'Product Companies',
    headquarters: 'Gurugram, Haryana, India',
    indiaLocations: ['Gurugram', 'Jaipur', 'Bengaluru', 'Pune', 'Hyderabad'],
    website: 'https://www.nagarro.com',
    companySize: '10,000+',
    foundedYear: 1996,
    isVerified: false,
    description: 'Global digital product engineering leader helping clients achieve competitive breakthroughs through fluid, agile engineering practices.',
  },
];

const mncCompanies = [
  {
    name: 'Accenture',
    category: 'MNC / Global Company',
    industry: 'Consulting',
    headquarters: 'Dublin, Ireland',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Mumbai', 'Pune', 'Chennai', 'Gurugram', 'Noida', 'Kolkata', 'Coimbatore', 'Jaipur'],
    website: 'https://www.accenture.com',
    companySize: '10,000+',
    foundedYear: 1989,
    isVerified: false,
    description: 'Global professional services company with leading capabilities in digital, cloud, security, strategy, and operations across India.',
  },
  {
    name: 'IBM',
    category: 'MNC / Global Company',
    industry: 'IT & Software',
    headquarters: 'Armonk, New York, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Pune', 'Mumbai', 'Gurugram', 'Noida', 'Chennai', 'Kolkata', 'Kochi', 'Ahmedabad'],
    website: 'https://www.ibm.com',
    companySize: '10,000+',
    foundedYear: 1911,
    isVerified: false,
    description: 'Multinational technology leader and hybrid cloud & AI powerhouse with major R&D and India Software Labs in multiple hubs.',
  },
  {
    name: 'Microsoft',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'Redmond, Washington, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Noida', 'Mumbai', 'Pune', 'Gurugram'],
    website: 'https://www.microsoft.com',
    companySize: '10,000+',
    foundedYear: 1975,
    isVerified: false,
    description: 'Global technology giant operating the Microsoft India Development Center (IDC), Azure engineering, and research centers in India.',
  },
  {
    name: 'Google',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'Mountain View, California, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Mumbai', 'Gurugram', 'Pune'],
    website: 'https://about.google',
    companySize: '10,000+',
    foundedYear: 1998,
    isVerified: false,
    description: 'Multinational technology conglomerate driving advancements in search, Android, cloud computing, and AI research in India.',
  },
  {
    name: 'Amazon',
    category: 'MNC / Global Company',
    industry: 'E-commerce',
    headquarters: 'Seattle, Washington, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Chennai', 'Mumbai', 'Pune', 'Delhi', 'Gurugram'],
    website: 'https://www.aboutamazon.in',
    companySize: '10,000+',
    foundedYear: 1994,
    isVerified: false,
    description: 'Global e-commerce and cloud computing (AWS) leader operating its largest worldwide corporate campus in Hyderabad, India.',
  },
  {
    name: 'Oracle',
    category: 'MNC / Global Company',
    industry: 'IT & Software',
    headquarters: 'Austin, Texas, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Pune', 'Mumbai', 'Noida', 'Chennai'],
    website: 'https://www.oracle.com',
    companySize: '10,000+',
    foundedYear: 1977,
    isVerified: false,
    description: 'Leader in enterprise cloud applications and infrastructure, database software, and autonomous cloud systems with major India operations.',
  },
  {
    name: 'Adobe',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'San Jose, California, USA',
    indiaLocations: ['Noida', 'Bengaluru'],
    website: 'https://www.adobe.com',
    companySize: '10,000+',
    foundedYear: 1982,
    isVerified: false,
    description: 'Global creator of multimedia and creativity software products and digital marketing platforms with extensive engineering labs in Noida and Bengaluru.',
  },
  {
    name: 'Deloitte',
    category: 'MNC / Global Company',
    industry: 'Consulting',
    headquarters: 'London, UK',
    indiaLocations: ['Hyderabad', 'Bengaluru', 'Mumbai', 'Gurugram', 'Pune', 'Chennai', 'Kolkata', 'Ahmedabad'],
    website: 'https://www.deloitte.com',
    companySize: '10,000+',
    foundedYear: 1845,
    isVerified: false,
    description: 'Top-tier audit, consulting, tax, and advisory services firm serving global and domestic enterprises from cutting-edge delivery centers in India.',
  },
  {
    name: 'EY',
    category: 'MNC / Global Company',
    industry: 'Consulting',
    headquarters: 'London, UK',
    indiaLocations: ['Bengaluru', 'Gurugram', 'Mumbai', 'Hyderabad', 'Kochi', 'Chennai', 'Kolkata', 'Pune', 'Noida'],
    website: 'https://www.ey.com',
    companySize: '10,000+',
    foundedYear: 1989,
    isVerified: false,
    description: 'Global leader in assurance, consulting, strategy, and tax services operating Global Delivery Services (GDS) across multiple Indian locations.',
  },
  {
    name: 'KPMG',
    category: 'MNC / Global Company',
    industry: 'Consulting',
    headquarters: 'Amstelveen, Netherlands',
    indiaLocations: ['Mumbai', 'Gurugram', 'Bengaluru', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Noida', 'Ahmedabad', 'Kochi'],
    website: 'https://www.kpmg.com',
    companySize: '10,000+',
    foundedYear: 1987,
    isVerified: false,
    description: 'Multinational professional services network providing audit, tax, and financial advisory consulting across major Indian metropolitan hubs.',
  },
  {
    name: 'PwC',
    category: 'MNC / Global Company',
    industry: 'Consulting',
    headquarters: 'London, UK',
    indiaLocations: ['Kolkata', 'Mumbai', 'Bengaluru', 'Gurugram', 'Hyderabad', 'Chennai', 'Pune', 'Ahmedabad'],
    website: 'https://www.pwc.in',
    companySize: '10,000+',
    foundedYear: 1998,
    isVerified: false,
    description: 'Leading professional services firm delivering human-led and tech-powered solutions in audit, tax, technology consulting, and risk advisory.',
  },
  {
    name: 'Capgemini',
    category: 'MNC / Global Company',
    industry: 'IT & Software',
    headquarters: 'Paris, France',
    indiaLocations: ['Bengaluru', 'Mumbai', 'Pune', 'Hyderabad', 'Chennai', 'Noida', 'Gurugram', 'Kolkata', 'Salem', 'Tiruchirappalli'],
    website: 'https://www.capgemini.com',
    companySize: '10,000+',
    foundedYear: 1967,
    isVerified: false,
    description: 'Global leader in partnering with companies to transform and manage their business through technology and engineering services.',
  },
  {
    name: 'Cognizant',
    category: 'MNC / Global Company',
    industry: 'IT & Software',
    headquarters: 'Teaneck, New Jersey, USA',
    indiaLocations: ['Chennai', 'Bengaluru', 'Hyderabad', 'Pune', 'Kolkata', 'Mumbai', 'Gurugram', 'Noida', 'Coimbatore', 'Kochi'],
    website: 'https://www.cognizant.com',
    companySize: '10,000+',
    foundedYear: 1994,
    isVerified: false,
    description: 'Multinational information technology services and consulting provider helping clients modernize technology, reimagine processes, and transform experiences.',
  },
  {
    name: 'SAP',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'Walldorf, Germany',
    indiaLocations: ['Bengaluru', 'Gurugram', 'Pune', 'Mumbai', 'Hyderabad'],
    website: 'https://www.sap.com',
    companySize: '10,000+',
    foundedYear: 1972,
    isVerified: false,
    description: 'Market leader in enterprise application software, operating SAP Labs India as its largest R&D hub outside Germany.',
  },
  {
    name: 'Salesforce',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'San Francisco, California, USA',
    indiaLocations: ['Hyderabad', 'Bengaluru', 'Mumbai', 'Gurugram', 'Pune', 'Jaipur'],
    website: 'https://www.salesforce.com',
    companySize: '10,000+',
    foundedYear: 1999,
    isVerified: false,
    description: 'World leader in AI CRM and cloud customer relationship management with major Center of Excellence hubs located in Hyderabad and Bengaluru.',
  },
  {
    name: 'Cisco',
    category: 'MNC / Global Company',
    industry: 'Telecommunications',
    headquarters: 'San Jose, California, USA',
    indiaLocations: ['Bengaluru', 'Mumbai', 'Gurugram', 'Hyderabad', 'Chennai', 'Pune'],
    website: 'https://www.cisco.com',
    companySize: '10,000+',
    foundedYear: 1984,
    isVerified: false,
    description: 'Worldwide leader in networking, secure connectivity, collaboration, and cybersecurity hardware, software, and services.',
  },
  {
    name: 'Intel',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'Santa Clara, California, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad'],
    website: 'https://www.intel.in',
    companySize: '10,000+',
    foundedYear: 1968,
    isVerified: false,
    description: 'Semiconductor industry titan developing silicon processors, graphics, and AI computing hardware with prominent design engineering centers in India.',
  },
  {
    name: 'Dell Technologies',
    category: 'MNC / Global Company',
    industry: 'IT & Software',
    headquarters: 'Round Rock, Texas, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Gurugram', 'Pune', 'Chennai', 'Noida'],
    website: 'https://www.dell.com',
    companySize: '10,000+',
    foundedYear: 1984,
    isVerified: false,
    description: 'Multinational technology company providing enterprise storage, servers, personal computing, and hybrid cloud solutions.',
  },
  {
    name: 'JPMorgan Chase',
    category: 'MNC / Global Company',
    industry: 'Banking & Finance',
    headquarters: 'New York, NY, USA',
    indiaLocations: ['Mumbai', 'Bengaluru', 'Hyderabad'],
    website: 'https://www.jpmorganchase.com',
    companySize: '10,000+',
    foundedYear: 1799,
    isVerified: false,
    description: 'Premier investment banking and financial services institution hosting major technology and corporate centers in Mumbai, Bengaluru, and Hyderabad.',
  },
  {
    name: 'Goldman Sachs',
    category: 'MNC / Global Company',
    industry: 'Banking & Finance',
    headquarters: 'New York, NY, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad'],
    website: 'https://www.goldmansachs.com',
    companySize: '5,000-10,000',
    foundedYear: 1869,
    isVerified: false,
    description: 'Global investment banking, securities, and investment management firm with extensive software engineering, quantitative analytics, and operations in India.',
  },
  {
    name: 'Morgan Stanley',
    category: 'MNC / Global Company',
    industry: 'Banking & Finance',
    headquarters: 'New York, NY, USA',
    indiaLocations: ['Mumbai', 'Bengaluru'],
    website: 'https://www.morganstanley.com',
    companySize: '5,000-10,000',
    foundedYear: 1935,
    isVerified: false,
    description: 'Global financial services firm operating major Global Centers in Mumbai and Bengaluru delivering technology, quantitative finance, and analytics.',
  },
  {
    name: 'Wells Fargo',
    category: 'MNC / Global Company',
    industry: 'Banking & Finance',
    headquarters: 'San Francisco, California, USA',
    indiaLocations: ['Hyderabad', 'Bengaluru', 'Chennai'],
    website: 'https://www.wellsfargo.com',
    companySize: '10,000+',
    foundedYear: 1852,
    isVerified: false,
    description: 'Diversified community-based financial services company operating Wells Fargo India across technology, risk modeling, and business services.',
  },
  {
    name: 'Siemens',
    category: 'MNC / Global Company',
    industry: 'Manufacturing',
    headquarters: 'Munich, Germany',
    indiaLocations: ['Bengaluru', 'Mumbai', 'Pune', 'Gurugram', 'Chennai', 'Kolkata'],
    website: 'https://www.siemens.com',
    companySize: '10,000+',
    foundedYear: 1847,
    isVerified: false,
    description: 'Technology powerhouse focused on industry, infrastructure, transport, and healthcare, with Siemens Technology and services operating across India.',
  },
  {
    name: 'Honeywell',
    category: 'MNC / Global Company',
    industry: 'Manufacturing',
    headquarters: 'Charlotte, North Carolina, USA',
    indiaLocations: ['Bengaluru', 'Hyderabad', 'Pune', 'Gurugram', 'Madurai'],
    website: 'https://www.honeywell.com',
    companySize: '10,000+',
    foundedYear: 1906,
    isVerified: false,
    description: 'Diversified technology and manufacturing enterprise delivering aerospace products, building technologies, and performance materials through Honeywell Technology Solutions.',
  },
  {
    name: 'NVIDIA',
    category: 'MNC / Global Company',
    industry: 'Product Companies',
    headquarters: 'Santa Clara, California, USA',
    indiaLocations: ['Bengaluru', 'Pune', 'Hyderabad', 'Gurugram'],
    website: 'https://www.nvidia.com',
    companySize: '1,000-5,000',
    foundedYear: 1993,
    isVerified: false,
    description: 'Pioneer of accelerated computing and graphics processing units (GPUs) driving generative AI, high-performance computing, and autonomous machines with engineering centers in India.',
  },
  {
    name: 'Qualcomm',
    category: 'MNC / Global Company',
    industry: 'Telecommunications',
    headquarters: 'San Diego, California, USA',
    indiaLocations: ['Hyderabad', 'Bengaluru', 'Chennai', 'Noida'],
    website: 'https://www.qualcomm.com',
    companySize: '10,000+',
    foundedYear: 1985,
    isVerified: false,
    description: 'World-leading wireless technology innovator developing 5G, mobile processors (Snapdragon), RF systems, and AI edge hardware with major engineering hubs in Hyderabad and Bengaluru.',
  },
];

module.exports = {
  indianCompanies,
  mncCompanies,
  allCompanies: [...indianCompanies, ...mncCompanies],
};
